#!/bin/bash
#SBATCH --job-name=prof
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=56
#SBATCH --time=3-00:00:00
## An email is sent when the job is canceled or finished
## Change "root" for your e-mail address
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=ejgonzalez@unc.edu.ar


. /etc/profile
source $HOME/.bashrc

##cd /mnt/projects/lensing/HALO_SHAPE/MICEv1.0/codes_HS_micev1.0/

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export MKL_NUM_THREADS=$SLURM_CPUS_PER_TASK

conda activate myenv

srun python -u forpair_profile.py -ncores 56 -sample 'newall_100_10000_zback' -nbins 20 -RIN 100 -ROUT 10000
srun python -u forpair_profile.py -ncores 56 -sample 'newall_100_10000_zback' -nbins 20 -RIN 100 -ROUT 10000 -pcat '_zspec_mask'
